name: gocover

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
    contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./...

    - name: Update coverage badge
      uses: ncruces/go-coverage-report@v0
